---
language: python
python:
  - "3.6"
install:
  pip install -r requirements.txt
script:
  python bimmer.py
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
