---
vehicle:
  vin: ~
  name: Runabout
account:
  username: ~
  password: ~
  country: north_america
logs:
  level: INFO
ifttt:
  event: charging_status
  api_key: ~
slack:
  webhook: ~
when:
  - INVALID
  - ERROR
  - NOT_CHARGING
  - WAITING_FOR_CHARGING
